---
title: "PS811 Statistical Computing in Political Science"
author: "Devin Judge-Lord"
subtitle: "University of Wisconsin-Madison"
date: 
output:
  html_document: 
    toc: false
    code_folding: hide
  pdf_document:
    toc: false
    citation_package: natbib
    fig_caption: yes
    keep_tex: no
    latex_engine: pdflatex
  word_document: 
    toc: false
header-includes:
  ## Add any Latex packages you need here (or use a preamble/template)
   - \usepackage{times}
---
JudgeLord@wisc.edu | 715.204.4287

Fridays 9-10 AM Soc Sci 6125, Jan. 25 - May 3

Office hours: Fridays 10-12 AM in the North Hall computer lab.

Required software: [R](https://www.rstudio.com/products/rstudio/download/#download), [LaTeX](https://www.latex-project.org/get/), [git](https://git-scm.com/downloads)

Materials will be on the course [website](https://judgelord.github.io/PS811/1-intro-to-PS811.html).

Students should clone this repository:

- In RStudio: File -> New Project -> Version Control -> Git -> [paste this URL] <https://github.com/judgelord/PS811> <[Instructions](https://github.com/judgelord/PS811/blob/master/github_instructions.md)>

# \#goals
This course builds core research skills to aid coursework for other stats classes and research papers:

## No-brainers 
- Keeping data tidy
- Writing readable code (e.g. pipe, don't nest)
- Writing efficient, easy-to-edit code (use functions, rarely copy & paste)
- Clearly presenting your data & results (tables, figures) 
- Never copy & paste tables or figures into a paper

---

## Worthwhile 
- Backing up / version control (e.g. git)
- Commenting your code 
- Being organized (e.g. project folders)
- Being portable (e.g. `here`)
- Breaking projects up into component parts

---

## Potential next steps
- Getting new data (e.g. web scraping & API's)
- Text analysis
- Classification 
- Dimension reduction
- Machine learning
- Duration modeling
- Surveys (e.g. qualtrics & mturk)
- Using remote servers

---

## Assignments

1. The first assignment is to write a problem set for a statistics class (e.g. 813) in a plain text notebook--- [R Markdown](http://rmarkdown.rstudio.com) or similar (e.g. [Jupyter](https://jupyter.org/)). (10%)


[Example Problem Set / Data Exercise](https://github.com/judgelord/PS811/raw/master/example_problem_set.pdf)

2. The remaining assignments are all incremental steps in producing a reproducible analysis of a dataset of your choosing. (50%)

[Example Portfolio](https://judgelord.github.io/PS811/example_portfolio.html)

Attendance: If you are solid on a week's topic and want to skip, this is totally fine, just show some work demonstrating this *ahead of time*. We may also use DataCamp tutorials to build or demonstrate skills as needed (i.e. according to your background knowledge and interests). (40%)

---

### 2. [R Markdown](https://judgelord.github.io/PS811/2-RMarkdown.html)

- Using [R Markdown](http://rmarkdown.rstudio.com)

- Class notes template
<[HTML](https://judgelord.github.io/PS811/example_notes.html)> 
<[PDF](https://github.com/judgelord/PS811/raw/master/example_notes.pdf)>

- [Problem set / Data exercise template](https://github.com/judgelord/PS811/raw/master/example_problem_set.pdf)


**Assignment 1:** Complete a problem set in R Markdown

---

### 3. Project folders and [git](https://judgelord.github.io/PS811/3-git.html)

**Assignment 2:** Publish your 811 webpage/portfolio on [GitHub](http://GitHub.com): Your research interests + potential questions, data, & methods

### 4. Tidy data + readable code 

- Nameing things
- Manipulating data with [`dplyr`](https://dplyr.tidyverse.org/) ( [cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf) ) & getting the most out of other `tidyverse` tools
- New variables with `mutate()` and `ifelse()`
- Pipes with `magrittr` (`%>%` and `%<>%`)
- Output (tables, `ggplot`)
- Commenting (`# R comment`, `% LaTeX comment`, `<!-- markdown / html coment -->`)

**Assignment 3:** Choose a dataset, edit variable names & values, do something cool with it. ***DUE: FEB 23**

---

### 5. Efficient code that does not break

- Project files (e.g. data, figs, functions)
- `here`
- Saving and loading data files
- Reproducible tables and figures

**Assignment 4:** Save your data and `setup.R` script to your 811 git repository, work on data summary, use `here()` for all file paths.


---

### 6. Summary analysis

- Presenting model results 
- More `ggplot` --- choosing layers (lines, intervals, colors, labels, facets, maps)

**Assignment 5:** Finish up initial data summary: clearly show what is most interesting or puzzling about your data. **DUE: MARCH 9**

Here is an [example portfolio](https://judgelord.github.io/PS811/1-intro-to-PS811.html) with a data summary that employs several of the tools we will have learned, including loading data, commenting code, renaming variables, making new variables, filtering data, building a custom function, pipes, adjusting figure size and labels, and a number of `ggplot` layers.

---

### 7. Data viz workshop - MARCH 16


- Bonus (optional): convert your 811 web page to a slideshow with `xaringan` (When you have to make a conference presentation, you'll be glad you did!)

---

### 8-(n-1). TBD

--- 

### n. Final data analysis presentations - MAY 3

---




## More resources and thanks!

Awesome previous 811 instructors: [Mike DeCrescenzo](https://mikedecr.github.io/), [Hannah Chapman](https://hannahschapman.com/), [Sarah Bouchat](https://bouchat.github.io/), Jack Edelson.

Similar courses by [Rochelle Terman](https://github.com/rochelleterman/PS239T), Rachel Bernhard, and [Jae Yeon Kim](https://github.com/jaeyk/PS239T).

Templates from Mike DeCrescenzo, Adam Lauretig, and Steven V. Miller. See [Mike's LaTeX workshop materials](https://mikedecr.github.io/code/)

---

## RULES, RIGHTS & RESPONSIBILITIES

•	See the Graduate Guide’s [Rules, Rights and Responsibilities](http://guide.wisc.edu/graduate/)

---

## ACADEMIC INTEGRITY

By enrolling in this course, each student assumes the responsibilities of an active participant in UW-Madison’s community of scholars in which everyone’s academic work and behavior are held to the highest academic integrity standards. Academic misconduct compromises the integrity of the university. Cheating, fabrication, plagiarism, unauthorized collaboration, and helping others commit these acts are examples of academic misconduct, which can result in disciplinary action. This includes but is not limited to failure on the assignment/course, disciplinary probation, or suspension. Substantial or repeated cases of misconduct will be forwarded to the Office of Student Conduct & Community Standards for additional review. For more information, refer to <http://studentconduct.wiscweb.wisc.edu/academic-integrity>

---

## ACCOMMODATIONS FOR STUDENTS WITH DISABILITIES

McBurney Disability Resource Center syllabus statement: “The University of Wisconsin-Madison supports the right of all enrolled students to a full and equal educational opportunity. The Americans with Disabilities Act (ADA), Wisconsin State Statute (36.12), and UW-Madison policy (Faculty Document 1071) require that students with disabilities be reasonably accommodated in instruction and campus life. Reasonable accommodations for students with disabilities is a shared faculty and student responsibility. Students are expected to inform faculty [me] of their need for instructional accommodations by the end of the third week of the semester, or as soon as possible after a disability has been incurred or recognized. Faculty [I], will work either directly with the student [you] or in coordination with the McBurney Center to identify and provide reasonable instructional accommodations. Disability information, including instructional accommodations as part of a student's educational record, is confidential and protected under FERPA.” <http://mcburney.wisc.edu/facstaffother/faculty/syllabus.php>

---

## DIVERSITY & INCLUSION

Institutional statement on diversity: “Diversity is a source of strength, creativity, and innovation for UW-Madison. We value the contributions of each person and respect the profound ways their identity, culture, background, experience, status, abilities, and opinion enrich the university community. We commit ourselves to the pursuit of excellence in teaching, research, outreach, and diversity as inextricably linked goals.

The University of Wisconsin-Madison fulfills its public mission by creating a welcoming and inclusive community for people from every background – people who as students, faculty, and staff serve Wisconsin and the world.” <https://diversity.wisc.edu/>
